
module.exports = {
   "Afghanistan":"af",
   "Albania":"al",
   "Algeria":"dz",
   "Argentina":"ar",
   "Armenia":"am",
   "Australia":"au",
   "Austria":"at",
   "Azerbaijan":"az",
   "Bahrain":"bh",
   "Bangladesh":"bd",
   "Barbados":"bb",
   "Belarus":"by",
   "Belgium":"be",
   "Bolivia":"bo",
   "Bosnia and Herzegovina":"ba",
   "Brazil":"br",
   "Bulgaria":"bg",
   "Cambodia":"kh",
   "Canada":"ca",
   "Chile":"cl",
   "China":"cn",
   "Congo":"cd",
   "Colombia":"co",
   "Costa Rica":"cr",
   "Croatia":"hr",
   "Cuba":"cu",
   "Cyprus":"cy",
   "Czech Republic":"cz",
   "Denmark":"dk",
   "Dominican Republic":"do",
   "Ecuador":"ec",
   "Egypt":"eg",
   "El Salvador":"sv",
   "Equatorial Guinea":"gq",
   "Estonia":"ee",
   "Finland":"fi",
   "France":"fr",
   "Georgia":"ge",
   "Germany":"de",
   "Ghana":"gh",
   "Greece":"gr",
   "Guatemala":"gt",
   "Guinea":"gn",
   "Guyana":"gy",
   "Haiti":"ht",
   "Honduras":"hn",
   "Hong Kong":"hk",
   "Hungary":"hu",
   "Iceland":"is",
   "India":"in",
   "Indonesia":"id",
   "Iran":"ir",
   "Iraq":"iq",
   "Ireland":"ie",
   "Israel":"il",
   "Italia":"it",
   "Ivory Coast":"ci",
   "Jamaica":"jm",
   "Japan":"jp",
   "Jordan":"jo",
   "Kazakhstan":"kz",
   "Kenya":"ke",
   "Kosovo":"xk",
   "Kuwait":"kw",
   "Kyrgyzstan":"kg",
   "Latvia":"lv",
   "Lebanon":"lb",
   "Libya":"ly",
   "Luxembourg":"lu",
   "Macau":"mo",
   "Macedonia":"mk",
   "Malaysia":"my",
   "Malta":"mt",
   "Mexico":"mx",
   "Moldova":"md",
   "Mongolia":"mn",
   "Montenegro":"me",
   "Morocco":"ma",
   "Mozambique":"mz",
   "Myanmar":"mm",
   "Nepal":"np",
   "Netherlands":"nl",
   "New Zealand":"nz",
   "Nicaragua":"ni",
   "Nigeria":"ng",
   "Norway":"no",
   "Oman":"om",
   "Pakistan":"pk",
   "Palestine":"ps",
   "Panama":"pa",
   "Paraguay":"py",
   "Peru":"pe",
   "Philippines":"ph",
   "Poland":"pl",
   "Portugal":"pt",
   "Puerto Rico":"pr",
   "Qatar":"qa",
   "Romania":"ro",
   "Russia":"ru",
   "Rwanda":"rw",
   "Saint Kitts and Nevis":"kn",
   "San Marino":"sm",
   "Saudi Arabia":"sa",
   "Serbia":"rs",
   "Singapore":"sg",
   "Slovakia":"sk",
   "Slovenia":"si",
   "South Korea":"kr",
   "Spain":"es",
   "Sri Lanka":"lk",
   "Sudan":"sd",
   "Sweden":"se",
   "Switzerland":"ch",
   "Syria":"sy",
   "Taiwan":"tw",
   "Thailand":"th",
   "Trinidad and Tobago":"tt",
   "Tunisia":"tn",
   "Turkey":"tr",
   "Turkmenistan":"tm",
   "Ukraine":"ua",
   "United Arab Emirates":"ae",
   "United Kingdom":"uk",
   "United States":"us",
   "Uruguay":"uy",
   "Uzbekistan":"uz",
   "Venezuela":"ve",
   "Vietnam":"vn",
   "Yemen":"ye"
}
